vich_uploader:
    db_driver: orm

    mappings:
        utilisateur_image:
            uri_prefix: /images/aliments
            upload_destination: '%kernel.project_dir%/public/images/aliments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        logo_image:
            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        offre_image:
            uri_prefix: /assets/images/packages
            upload_destination: '%kernel.project_dir%/public/assets/images/packages/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        pays_image:
            uri_prefix: /assets/images/gallary
            upload_destination: '%kernel.project_dir%/public/assets/images/gallary/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
